name: Update anti-AD rules

on:
  push:
    branches: [master]
  schedule:
    - cron: 0 * * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create dist folder
        run: mkdir -p dist

      - name: Get rule
        run: |
          curl -o dist/adblock-for-dnsmasq.conf https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf

      - name: Remove from whitelist
        run: |
          cat whitelist.lst | while read line
          do
            echo "${line}"
            sed -i "/${line}/d" dist/adblock-for-dnsmasq.conf
          done

      - name: Commit artifacts to release branch
        id: commt
        run: |
          git config --local user.email "769910+fgprodigal@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release
          #git checkout --orphan release-orphan
          #git rm -rf .
          cp -f dist/* .
          rm -rf dist
          #git branch -D release
          #git branch -m release

          if [[ `git status --porcelain` ]]; then
            git add adblock-for-dnsmasq.conf
            git commit -am "Updated at $(date)"
            echo "::set-output name=changes::true"
          fi

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        if: steps.commit.outputs.changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true

      - name: Purge jsDelivr
        if: steps.commit.outputs.changes
        run: |
          curl https://purge.jsdelivr.net/gh/fgprodigal/anti-AD@release/adblock-for-dnsmasq.conf

