name: Update anti-AD rules

on:
  push:
    branches: [master]
    paths:
      - '.github/**'
      - 'config/**'
  schedule:
    - cron: 0 * * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone repository
        run: git clone https://github.com/fgprodigal/anti-AD.git anti-AD

      - name: Create directory
        run: mkdir rules

      - name: Get rule
        run: |
          curl -o rules/adblock-for-dnsmasq.conf https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
          curl -o rules/anti-ad-domains.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
          curl -o rules/anti-ad-easylist.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
          curl -o rules/anti-ad-smartdns.conf https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf
          curl -o rules/anti-ad-surge.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
          curl -o rules/anti-ad-surge2.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt

      - name: Remove from whitelist
        run: |
          cat config/whitelist.lst | while read line
          do
            echo "Removing ${line} .."
            sed -i "/${line}/d" rules/adblock-for-dnsmasq.conf
            sed -i "/${line}/d" rules/anti-ad-domains.txt
            sed -i "/${line}/d" rules/anti-ad-easylist.txt
            sed -i "/${line}/d" rules/anti-ad-smartdns.conf
            sed -i "/${line}/d" rules/anti-ad-surge.txt
            sed -i "/${line}/d" rules/anti-ad-surge2.txt
          done

      - name: Git commit
        id: commit
        run: |
          cd anti-AD
          cp ../rules/* .
          git config --local user.email "769910+fgprodigal@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git add -A
          if ! git diff-index --quiet --cached HEAD; then
            git commit -am "Auto updated at $(date)"
            echo "::set-output name=changes::true"
          fi

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        if: steps.commit.outputs.changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          directory: 'anti-AD'

      - name: Purge jsDelivr
        if: steps.commit.outputs.changes
        run: |
          curl https://purge.jsdelivr.net/gh/fgprodigal/anti-AD@master/adblock-for-dnsmasq.conf
